project:
  type: website
  output-dir: docs

website:
  title: "Martin Tran"
  navbar:
    left:
      - href: index.qmd
        text: home
      
      - text: projects
        menu: 
          - href: sql_project.qmd
            text: SQL project
          - href: text_analysis.qmd
            text: text analysis project
          - href: Rpackage.qmd
            text: dogR
          - href: poster.html
            text: History of S & R
            
      - href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true