project:
  type: website
  output-dir: docs

website:
  title: "Martin Tran"
  site-url: https://Martin-Tra.github.io/
  repo-url: https://github.com/Martin-Tra/Martin-Tra.github.io
  favicon: images/Pokemon.png
  navbar:
    left:
      - href: index.qmd
        text: home
      
      - text: projects
        menu: 
          - href: sql_project.qmd
            text: SQL project
          - href: text_analysis.qmd
            text: Text Analysis Project
          - href: Rpackage.qmd
            text: dogR
          - href: poster.qmd
            text: History of S & R
          - href: Automation_Report.qmd
            text: Datathon Automation
            
      - href: about.qmd
        text: About
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true